name: Pulumi Apply
on:
  push:
    branches:
      - main
    paths:
      - "iac/**"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - run: go mod download
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: GuanceCloud/community/github
          work-dir: internal/iac/github
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GUANCE_BOT_TOKEN }}
          GITHUB_OWNER: GuanceCloud
